# Generated by Django 5.0.2 on 2024-03-18 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description_short", models.TextField(max_length=255)),
                ("description_long", models.TextField()),
                ("image", models.ImageField(upload_to="produt_image/%Y/%m/")),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                ("price_marketing", models.FloatField()),
                ("price_marketing_promotional", models.FloatField(default=0)),
                (
                    "type_variation",
                    models.CharField(
                        choices=[("V", "Variavel"), ("S", "Simples")],
                        default="v",
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImagesProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_products",
                    models.ImageField(
                        blank=True, null=True, upload_to="produt_image_var/%Y/%m/"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductTabell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "information",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Variation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "image_var",
                    models.ImageField(upload_to="produt_image_variation/%Y/%m/"),
                ),
                ("preco", models.FloatField()),
                ("preco_promotional", models.FloatField(default=0)),
                ("estoque", models.PositiveIntegerField(default=1)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
            ],
        ),
    ]
