# Generated by Django 5.0.2 on 2024-03-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variation",
            name="image_var",
            field=models.ImageField(
                blank=True, null=True, upload_to="produt_image_variation/%Y/%m/"
            ),
        ),
    ]
