# Generated by Django 5.0.2 on 2024-02-13 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_variacao"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Produto",
            new_name="Product",
        ),
        migrations.RenameModel(
            old_name="Variacao",
            new_name="Variation",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="nome",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="variation",
            old_name="nome",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="variation",
            old_name="produto",
            new_name="product",
        ),
    ]
