# Generated by Django 5.0.2 on 2024-02-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="produt_image/%Y/%m/"),
        ),
    ]
