# Generated by Django 5.0.2 on 2024-02-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_alter_product_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImagemBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagem_banner", models.ImageField(upload_to="banners/")),
            ],
        ),
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                (
                    "imagens_banner",
                    models.ManyToManyField(
                        related_name="banners", to="product.imagembanner"
                    ),
                ),
            ],
        ),
    ]
