# Generated by Django 5.0.2 on 2024-03-16 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_variation_image_var"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductTabell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coluna_1", models.CharField(max_length=255)),
                ("coluna_2", models.CharField(max_length=255)),
                ("coluna_3", models.CharField(max_length=255)),
                ("coluna_4", models.CharField(max_length=255)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
            ],
        ),
    ]
