# Generated by Django 5.0.2 on 2024-02-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_imagembanner_banner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="banner",
            name="titulo",
        ),
        migrations.AlterField(
            model_name="imagembanner",
            name="imagem_banner",
            field=models.ImageField(upload_to="banner/%Y/%m/"),
        ),
    ]
