# Generated by Django 5.0.2 on 2024-03-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_producttabell"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producttabell",
            name="coluna_1",
        ),
        migrations.RemoveField(
            model_name="producttabell",
            name="coluna_2",
        ),
        migrations.RemoveField(
            model_name="producttabell",
            name="coluna_3",
        ),
        migrations.RemoveField(
            model_name="producttabell",
            name="coluna_4",
        ),
        migrations.AddField(
            model_name="producttabell",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="producttabell",
            name="information",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
