# Generated by Django 5.0.2 on 2024-03-17 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_remove_producttabell_coluna_1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variation",
            name="image_var",
        ),
        migrations.CreateModel(
            name="VariationImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_var",
                    models.ImageField(
                        blank=True, null=True, upload_to="produt_image_var/%Y/%m/"
                    ),
                ),
                (
                    "variation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="product.variation",
                    ),
                ),
            ],
        ),
    ]
