# Generated by Django 5.0.2 on 2024-03-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0011_variationimage_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="variation",
            name="image_varr",
            field=models.ImageField(
                blank=True, null=True, upload_to="product_image_var/%Y/%m/"
            ),
        ),
    ]
