# Generated by Django 5.0.2 on 2024-03-18 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0012_variation_image_varr"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variation",
            name="image_varr",
        ),
        migrations.RemoveField(
            model_name="variationimage",
            name="variation",
        ),
        migrations.AddField(
            model_name="variation",
            name="images",
            field=models.ManyToManyField(to="product.variationimage"),
        ),
        migrations.AlterField(
            model_name="variationimage",
            name="product",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
            ),
        ),
    ]
