# Generated by Django 5.0.2 on 2024-03-18 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0013_remove_variation_image_varr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variationimage",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
            ),
        ),
    ]
