# Generated by Django 5.0.2 on 2024-02-13 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product", models.CharField(max_length=255)),
                ("product_id", models.PositiveIntegerField()),
                ("variation", models.CharField(max_length=255)),
                ("variation_id", models.PositiveIntegerField()),
                ("price", models.FloatField()),
                ("promotional_price", models.FloatField(default=0)),
                ("quantity", models.PositiveIntegerField()),
                ("image", models.URLField(max_length=2000)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="order.order"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="OrdenItem",
        ),
    ]
